# Generated by Django 5.0 on 2024-10-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_app',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='nombreUsuario')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
